import nh from '@/asset/bank/nh.png';
import mg from '@/asset/bank/mg.png';
import cu from '@/asset/bank/cu.png';
import sh from '@/asset/bank/sh.png';
import shinhan from '@/asset/bank/shinhan.png';
import woori from '@/asset/bank/woori.png';

export const branchLocations = {
  농협은행: [
    {
      lat: 37.538,
      lng: 127.082,
      name: '건대입구점',
      address: '서울 광진구 능동로 150',
    },
    {
      lat: 37.511,
      lng: 127.098,
      name: '잠실점',
      address: '서울 송파구 올림픽로 300',
    },
    {
      lat: 37.503,
      lng: 127.026,
      name: '강남본점',
      address: '서울 강남구 강남대로 400',
    },
    {
      lat: 37.519,
      lng: 127.047,
      name: '청담점',
      address: '서울 강남구 언주로 700',
    },
    {
      lat: 37.533,
      lng: 127.085,
      name: '자양점',
      address: '서울 광진구 아차산로 400',
    },
  ],
  신한은행: [
    {
      lat: 37.536,
      lng: 127.092,
      name: '구의점',
      address: '서울 광진구 구의로 250',
    },
    {
      lat: 37.514,
      lng: 127.106,
      name: '잠실역점',
      address: '서울 송파구 올림픽로 500',
    },
    {
      lat: 37.501,
      lng: 127.035,
      name: '역삼점',
      address: '서울 강남구 테헤란로 300',
    },
    {
      lat: 37.524,
      lng: 127.051,
      name: '청담본점',
      address: '서울 강남구 도산대로 400',
    },
    {
      lat: 37.546,
      lng: 127.071,
      name: '중곡점',
      address: '서울 광진구 동일로 300',
    },
  ],
  우리은행: [
    {
      lat: 37.539,
      lng: 127.067,
      name: '군자점',
      address: '서울 광진구 능동로 200',
    },
    {
      lat: 37.512,
      lng: 127.082,
      name: '석촌점',
      address: '서울 송파구 백제고분로 400',
    },
    {
      lat: 37.504,
      lng: 127.02,
      name: '논현점',
      address: '서울 강남구 논현로 600',
    },
    {
      lat: 37.522,
      lng: 127.058,
      name: '삼성점',
      address: '서울 강남구 삼성로 600',
    },
    {
      lat: 37.544,
      lng: 127.082,
      name: '화양점',
      address: '서울 광진구 아차산로 200',
    },
  ],
  새마을금고: [
    {
      lat: 37.542,
      lng: 127.069,
      name: '어린이대공원점',
      address: '서울 광진구 능동로 250',
    },
    {
      lat: 37.516,
      lng: 127.1,
      name: '잠실나루점',
      address: '서울 송파구 올림픽로 350',
    },
    {
      lat: 37.502,
      lng: 127.037,
      name: '역삼점',
      address: '서울 강남구 역삼로 300',
    },
    {
      lat: 37.521,
      lng: 127.045,
      name: '압구정점',
      address: '서울 강남구 도산대로 500',
    },
    {
      lat: 37.548,
      lng: 127.078,
      name: '구의점',
      address: '서울 광진구 아차산로 350',
    },
  ],
  신협: [
    {
      lat: 37.541,
      lng: 127.065,
      name: '군자동점',
      address: '서울 광진구 능동로 180',
    },
    {
      lat: 37.513,
      lng: 127.09,
      name: '석촌호수점',
      address: '서울 송파구 석촌호수로 300',
    },
    {
      lat: 37.505,
      lng: 127.03,
      name: '삼성점',
      address: '서울 강남구 테헤란로 400',
    },
    {
      lat: 37.523,
      lng: 127.05,
      name: '청담역점',
      address: '서울 강남구 언주로 800',
    },
    {
      lat: 37.537,
      lng: 127.072,
      name: '중곡점',
      address: '서울 광진구 아차산로 250',
    },
  ],
  수협은행: [
    {
      lat: 37.543,
      lng: 127.07,
      name: '화양점',
      address: '서울 광진구 능동로 300',
    },
    {
      lat: 37.515,
      lng: 127.097,
      name: '잠실본점',
      address: '서울 송파구 올림픽로 450',
    },
    {
      lat: 37.5,
      lng: 127.028,
      name: '논현점',
      address: '서울 강남구 강남대로 350',
    },
    {
      lat: 37.52,
      lng: 127.04,
      name: '압구정점',
      address: '서울 강남구 도산대로 600',
    },
    {
      lat: 37.547,
      lng: 127.075,
      name: '자양점',
      address: '서울 광진구 아차산로 300',
    },
  ],
};

export const allProducts = {
  예금: [
    {
      id: 1,
      bank: '농협은행',
      title: 'NH 외화 정기예금',
      logo: nh,
      basicrate: 2.3,
      maximumrate: 3.2,
      period: 12,
      preferential: '급여 이체 시 우대금리 +0.2%',
      website: 'https://www.nonghyup.com/',
      callcenter: '+82-2-2080-3000',
    },
    {
      id: 2,
      bank: '신한은행',
      title: '신한 스마트 예금',
      logo: shinhan,
      basicrate: 2.4,
      maximumrate: 3.3,
      period: 6,
      preferential: '자동이체 등록 시 우대금리 +0.1%',
      website: 'https://www.shinhan.com/',
      callcenter: '+82-2-1577-8380',
    },
    {
      id: 3,
      bank: '우리은행',
      title: '우리 프리미엄 예금',
      logo: woori,
      basicrate: 2.5,
      maximumrate: 3.4,
      period: 24,
      preferential: '신규 가입 시 우대금리 +0.3%',
      website: 'https://www.wooribank.com/',
      callcenter: '+82-2-2002-5000',
    },
    {
      id: 4,
      bank: '새마을금고',
      title: 'MG 우대 예금',
      logo: mg,
      basicrate: 2.6,
      maximumrate: 3.5,
      period: 12,
      preferential: '온라인 가입 시 우대금리 +0.2%',
      website: 'https://www.kfcc.co.kr/',
      callcenter: '+82-2-1599-9000',
    },
    {
      id: 5,
      bank: '신협',
      title: '신협 고금리 예금',
      logo: cu,
      basicrate: 2.7,
      maximumrate: 3.6,
      period: 36,
      preferential: '자동이체 + 가족 계좌 연계 시 우대',
      website: 'https://www.cu.co.kr/',
      callcenter: '+82-2-1566-6000',
    },
    {
      id: 6,
      bank: '수협은행',
      title: '수협 해양 예금',
      logo: sh,
      basicrate: 2.8,
      maximumrate: 3.7,
      period: 18,
      preferential: '해양 종사자 우대금리 +0.3%',
      website: 'https://www.suhyup-bank.com/',
      callcenter: '+82-2-1588-1515',
    },
    {
      id: 7,
      bank: '농협은행',
      title: 'NH 플러스 예금',
      logo: nh,
      basicrate: 2.9,
      maximumrate: 3.8,
      period: 12,
      preferential: '모바일 신규 가입 시 우대금리 +0.2%',
      website: 'https://www.nonghyup.com/',
      callcenter: '+82-2-2080-3000',
    },
    {
      id: 8,
      bank: '신한은행',
      title: '신한 모바일 예금',
      logo: shinhan,
      basicrate: 2.5,
      maximumrate: 3.5,
      period: 6,
      preferential: '첫 모바일 거래 고객 우대',
      website: 'https://www.shinhan.com/',
      callcenter: '+82-2-1577-8380',
    },
    {
      id: 9,
      bank: '우리은행',
      title: '우리 스텝업 예금',
      logo: woori,
      basicrate: 2.6,
      maximumrate: 3.6,
      period: 24,
      preferential: '월 납입액 증가 시 우대금리',
      website: 'https://www.wooribank.com/',
      callcenter: '+82-2-2002-5000',
    },
    {
      id: 10,
      bank: '새마을금고',
      title: 'MG 특별 예금',
      logo: mg,
      basicrate: 2.7,
      maximumrate: 3.7,
      period: 12,
      preferential: '우수 고객 등급 우대금리 +0.3%',
      website: 'https://www.kfcc.co.kr/',
      callcenter: '+82-2-1599-9000',
    },
  ],
};

allProducts.적금 = [
  {
    id: 11,
    bank: '신협',
    title: '신협 청년 적금',
    logo: cu,
    basicrate: 2.8,
    maximumrate: 3.7,
    period: 12,
    preferential: '청년(19~34세) 우대금리 +0.4%',
    website: 'https://www.cu.co.kr/',
    callcenter: '+82-2-1566-6000',
  },
  {
    id: 12,
    bank: '수협은행',
    title: '수협 해양 적금',
    logo: sh,
    basicrate: 2.9,
    maximumrate: 3.8,
    period: 24,
    preferential: '해양 종사자 우대금리 +0.3%',
    website: 'https://www.suhyup-bank.com/',
    callcenter: '+82-2-1588-1515',
  },
  {
    id: 13,
    bank: '농협은행',
    title: 'NH 주택마련 적금',
    logo: nh,
    basicrate: 2.5,
    maximumrate: 3.4,
    period: 36,
    preferential: '주택청약 가입자 우대금리 +0.2%',
    website: 'https://www.nonghyup.com/',
    callcenter: '+82-2-2080-3000',
  },
  {
    id: 14,
    bank: '신한은행',
    title: '신한 스마트 적금',
    logo: shinhan,
    basicrate: 2.6,
    maximumrate: 3.5,
    period: 12,
    preferential: '자동이체 3회 이상 시 우대',
    website: 'https://www.shinhan.com/',
    callcenter: '+82-2-1577-8380',
  },
  {
    id: 15,
    bank: '우리은행',
    title: '우리 장기 적금',
    logo: woori,
    basicrate: 2.7,
    maximumrate: 3.6,
    period: 24,
    preferential: '월 납입액 10만 원 이상 우대금리',
    website: 'https://www.wooribank.com/',
    callcenter: '+82-2-2002-5000',
  },
  {
    id: 16,
    bank: '새마을금고',
    title: 'MG 우대 적금',
    logo: mg,
    basicrate: 2.8,
    maximumrate: 3.7,
    period: 18,
    preferential: '기존 고객 + 자동이체 시 우대',
    website: 'https://www.kfcc.co.kr/',
    callcenter: '+82-2-1599-9000',
  },
  {
    id: 17,
    bank: '신협',
    title: '신협 스텝업 적금',
    logo: cu,
    basicrate: 2.9,
    maximumrate: 3.8,
    period: 12,
    preferential: '월별 납입금 상승 시 우대금리',
    website: 'https://www.cu.co.kr/',
    callcenter: '+82-2-1566-6000',
  },
  {
    id: 18,
    bank: '수협은행',
    title: '수협 청년 적금',
    logo: sh,
    basicrate: 2.5,
    maximumrate: 3.5,
    period: 12,
    preferential: '청년 신규 가입자 우대',
    website: 'https://www.suhyup-bank.com/',
    callcenter: '+82-2-1588-1515',
  },
  {
    id: 19,
    bank: '농협은행',
    title: 'NH 자동이체 적금',
    logo: nh,
    basicrate: 2.6,
    maximumrate: 3.6,
    period: 6,
    preferential: '자동이체 2건 이상 시 우대',
    website: 'https://www.nonghyup.com/',
    callcenter: '+82-2-2080-3000',
  },
  {
    id: 20,
    bank: '신한은행',
    title: '신한 특별 적금',
    logo: shinhan,
    basicrate: 2.7,
    maximumrate: 3.7,
    period: 24,
    preferential: '신규 거래 고객 우대금리 +0.3%',
    website: 'https://www.shinhan.com/',
    callcenter: '+82-2-1577-8380',
  },
];

allProducts['신용 대출'] = [
  {
    id: 21,
    bank: '우리은행',
    title: '우리 신용대출',
    logo: woori,
    basicrate: 4.0,
    maximumrate: 5.0,
    period: 12,
    preferential: '급여 이체 시 우대금리 -0.3%',
    website: 'https://www.wooribank.com/',
    callcenter: '+82-2-2002-5000',
  },
  {
    id: 22,
    bank: '새마을금고',
    title: 'MG 간편대출',
    logo: mg,
    basicrate: 4.1,
    maximumrate: 5.1,
    period: 24,
    preferential: 'MG카드 사용 시 금리 인하',
    website: 'https://www.kfcc.co.kr/',
    callcenter: '+82-2-1599-9000',
  },
  {
    id: 23,
    bank: '신협',
    title: '신협 모바일대출',
    logo: cu,
    basicrate: 4.2,
    maximumrate: 5.2,
    period: 6,
    preferential: '모바일 신청 고객 우대금리 -0.2%',
    website: 'https://www.cu.co.kr/',
    callcenter: '+82-2-1566-6000',
  },
  {
    id: 24,
    bank: '수협은행',
    title: '수협 직장인대출',
    logo: sh,
    basicrate: 4.3,
    maximumrate: 5.3,
    period: 36,
    preferential: '급여통장 사용 시 금리 인하',
    website: 'https://www.suhyup-bank.com/',
    callcenter: '+82-2-1588-1515',
  },
  {
    id: 25,
    bank: '농협은행',
    title: 'NH 급전대출',
    logo: nh,
    basicrate: 4.4,
    maximumrate: 5.4,
    period: 12,
    preferential: '자동이체 1건 이상 시 인하',
    website: 'https://www.nonghyup.com/',
    callcenter: '+82-2-2080-3000',
  },
  {
    id: 26,
    bank: '신한은행',
    title: '신한 중금리대출',
    logo: shinhan,
    basicrate: 4.5,
    maximumrate: 5.5,
    period: 24,
    preferential: '신용점수 우수 고객 우대',
    website: 'https://www.shinhan.com/',
    callcenter: '+82-2-1577-8380',
  },
  {
    id: 27,
    bank: '우리은행',
    title: '우리 비대면대출',
    logo: woori,
    basicrate: 4.6,
    maximumrate: 5.6,
    period: 18,
    preferential: '비대면 신규 가입 시 우대',
    website: 'https://www.wooribank.com/',
    callcenter: '+82-2-2002-5000',
  },
  {
    id: 28,
    bank: '새마을금고',
    title: 'MG 프리미엄대출',
    logo: mg,
    basicrate: 4.7,
    maximumrate: 5.7,
    period: 12,
    preferential: 'VIP 등급 고객 금리 인하',
    website: 'https://www.kfcc.co.kr/',
    callcenter: '+82-2-1599-9000',
  },
  {
    id: 29,
    bank: '신협',
    title: '신협 우대대출',
    logo: cu,
    basicrate: 4.3,
    maximumrate: 5.3,
    period: 6,
    preferential: '신협 카드 이용 실적 우대',
    website: 'https://www.cu.co.kr/',
    callcenter: '+82-2-1566-6000',
  },
  {
    id: 30,
    bank: '수협은행',
    title: '수협 스텝업대출',
    logo: sh,
    basicrate: 4.2,
    maximumrate: 5.2,
    period: 36,
    preferential: '해양 종사자 우대',
    website: 'https://www.suhyup-bank.com/',
    callcenter: '+82-2-1588-1515',
  },
];

allProducts['전세 대출'] = [
  {
    id: 31,
    bank: '농협은행',
    title: 'NH 주택 전세대출',
    logo: nh,
    basicrate: 3.1,
    maximumrate: 4.0,
    period: 24,
    preferential: '주택청약 가입 시 우대금리',
    website: 'https://www.nonghyup.com/',
    callcenter: '+82-2-2080-3000',
  },
  {
    id: 32,
    bank: '신한은행',
    title: '신한 전세자금대출',
    logo: shinhan,
    basicrate: 3.2,
    maximumrate: 4.1,
    period: 12,
    preferential: '신규 고객 금리 인하',
    website: 'https://www.shinhan.com/',
    callcenter: '+82-2-1577-8380',
  },
  {
    id: 33,
    bank: '우리은행',
    title: '우리 전세대출',
    logo: woori,
    basicrate: 3.3,
    maximumrate: 4.2,
    period: 18,
    preferential: '자동이체 2건 이상 우대',
    website: 'https://www.wooribank.com/',
    callcenter: '+82-2-2002-5000',
  },
  {
    id: 34,
    bank: '새마을금고',
    title: 'MG 주택자금대출',
    logo: mg,
    basicrate: 3.4,
    maximumrate: 4.3,
    period: 12,
    preferential: 'MG카드 사용 시 우대금리',
    website: 'https://www.kfcc.co.kr/',
    callcenter: '+82-2-1599-9000',
  },
  {
    id: 35,
    bank: '신협',
    title: '신협 전세대출',
    logo: cu,
    basicrate: 3.5,
    maximumrate: 4.4,
    period: 24,
    preferential: '우량고객 등급 금리 인하',
    website: 'https://www.cu.co.kr/',
    callcenter: '+82-2-1566-6000',
  },
  {
    id: 36,
    bank: '수협은행',
    title: '수협 해양 전세대출',
    logo: sh,
    basicrate: 3.6,
    maximumrate: 4.5,
    period: 36,
    preferential: '해양 종사자 우대금리',
    website: 'https://www.suhyup-bank.com/',
    callcenter: '+82-2-1588-1515',
  },
  {
    id: 37,
    bank: '농협은행',
    title: 'NH 특판 전세대출',
    logo: nh,
    basicrate: 3.7,
    maximumrate: 4.6,
    period: 18,
    preferential: '자동이체 등록 시 우대금리',
    website: 'https://www.nonghyup.com/',
    callcenter: '+82-2-2080-3000',
  },
  {
    id: 38,
    bank: '신한은행',
    title: '신한 우대 전세대출',
    logo: shinhan,
    basicrate: 3.8,
    maximumrate: 4.7,
    period: 12,
    preferential: '신용점수 우수 고객 금리 인하',
    website: 'https://www.shinhan.com/',
    callcenter: '+82-2-1577-8380',
  },
  {
    id: 39,
    bank: '우리은행',
    title: '우리 스텝업 전세대출',
    logo: woori,
    basicrate: 3.9,
    maximumrate: 4.8,
    period: 24,
    preferential: '월 상환액 증가 시 우대금리',
    website: 'https://www.wooribank.com/',
    callcenter: '+82-2-2002-5000',
  },
  {
    id: 40,
    bank: '새마을금고',
    title: 'MG 스마트 전세대출',
    logo: mg,
    basicrate: 4.0,
    maximumrate: 4.9,
    period: 12,
    preferential: '온라인 신규 가입자 우대',
    website: 'https://www.kfcc.co.kr/',
    callcenter: '+82-2-1599-9000',
  },
];
