export const bankNameMap = {
  국민은행: 'kb',
  신한은행: 'shinhan',
  하나은행: 'hana',
  우리은행: 'woori',
  농협은행: 'nh',
  기업은행: 'ibk',
  제일은행: 'sc',
  카카오뱅크: 'kakao',
  토스뱅크: 'toss',
  케이뱅크: 'k',
  씨티은행: 'city',
  대구은행: 'dgb',
  부산은행: 'busan',
  경남은행: 'busan',
  광주은행: 'gwangju',
  전북은행: 'gwangju',
  우체국: 'post',
  수협은행: 'sh',
  산업은행: 'kdb',
  제주은행: 'im',
  신협은행: 'cu',
  새마을금고: 'mg',
};
