export const bankEngNameMap = {
  국민은행: 'kb',
  신한은행: 'shinhan',
  하나은행: 'hana',
  우리은행: 'woori',
  농협은행: 'nh',
  기업은행: 'ibk',
  제일은행: 'sc',
  카카오뱅크: 'kakao',
  토스뱅크: 'toss',
  케이뱅크: 'k',
  씨티은행: 'city',
  대구은행: 'dgb',
  부산은행: 'busan',
  경남은행: 'busan',
  광주은행: 'gwangju',
  전북은행: 'gwangju',
  우체국: 'post',
  수협은행: 'sh',
  산업은행: 'kdb',
  제주은행: 'shinhan',
  아이엠뱅크: 'im',
  신협은행: 'cu',
  새마을금고: 'mg',
};

export const bankKorNameMap = {
  kb: '국민은행',
  shinhan: '신한은행',
  hana: '하나은행',
  woori: '우리은행',
  nh: '농협은행',
  ibk: '기업은행',
  sc: '제일은행',
  kakao: '카카오뱅크',
  toss: '토스뱅크',
  k: '케이뱅크',
  city: '씨티은행',
  dgb: '대구은행',
  busan: '경남은행',
  gwangju: '전북은행',
  post: '우체국',
  sh: '수협은행',
  kdb: '산업은행',
  im: '아이엠뱅크',
  cu: '신협은행',
  mg: '새마을금고',
  jeonbuk: '전북은행',
};

export const conditionNameMap = {
  ONLINE: '비대면가입',
  BANK_APP: '은행앱사용',
  USING_CARD: '카드사용',
  USING_SALARY_ACCOUNT: '급여연동',
  USING_UTILITY_BILL: '공과금연동',
  FIRST_BANKING: '첫거래',
  DEPOSIT_ACCOUNT: '입출금통장',
  DEPOSIT_AGAIN: '재예치',
  HOUSING_SUBSCRIPTION: '주택청약',
  AUTO_DEPOSIT: '자동이체',
  RECOMMEND_COUPON: '추천',
  ETC: '기타',
};

export const periodNameMap = {
  '6개월': 'SIX_MONTH',
  '12개월': 'ONE_YEAR',
  '24개월': 'TWO_YEAR',
  체류기간: 'STAY_EXPIRATION',
};
